-- CLIENTE
INSERT INTO CLIENTE VALUES (1, 'Joao Silva', 'Rua A', '11999999999', 'A');
INSERT INTO CLIENTE VALUES (2, 'Maria Souza', 'Rua B', '11888888888', 'A');

-- CATEGORIA
INSERT INTO CATEGORIA VALUES (1, 'Frutas');
INSERT INTO CATEGORIA VALUES (2, 'Gourmet');

-- SORVETE
INSERT INTO SORVETE VALUES (1, 'Morango', 10.00, 1);
INSERT INTO SORVETE VALUES (2, 'Chocolate Belga', 15.00, 2);

-- INGREDIENTE
INSERT INTO INGREDIENTE VALUES (1, 'Leite');
INSERT INTO INGREDIENTE VALUES (2, 'Acucar');

-- SORVETE_INGREDIENTE
INSERT INTO SORVETE_INGREDIENTE VALUES (1, 1);
INSERT INTO SORVETE_INGREDIENTE VALUES (1, 2);
INSERT INTO SORVETE_INGREDIENTE VALUES (2, 1);

-- VENDA
INSERT INTO VENDA VALUES (1, 1, DATE '2024-05-01', 2, 10.00);
INSERT INTO VENDA VALUES (2, 2, DATE '2024-05-02', 1, 15.00);
