CREATE TABLE DEPARTAMENTO 
    ( 
     ID_DEP    NUMBER (3)  NOT NULL , 
     NOME_DEP  VARCHAR2 (40) , 
     LOCAL_DEP VARCHAR2 (50) 
    ) 

ALTER TABLE DEPARTAMENTO 
    ADD CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY ( ID_DEP ) ;
    
CREATE TABLE EMPREGADO 
    ( 
     ID_EMP              NUMBER (6)  NOT NULL , 
     NOME                VARCHAR2 (40) , 
     SALARIO             NUMBER (9,2) , 
     DEPARTAMENTO_ID_DEP NUMBER (3)  NOT NULL 
    )

ALTER TABLE EMPREGADO 
    ADD CONSTRAINT EMPREGADO_PK PRIMARY KEY ( ID_EMP ) ;
    
ALTER TABLE EMPREGADO 
    ADD CONSTRAINT EMPREGADO_DEPARTAMENTO_FK FOREIGN KEY 
    ( 
     DEPARTAMENTO_ID_DEP
    ) 
    REFERENCES DEPARTAMENTO 
    ( 
     ID_DEP
    )
    
INSERT INTO DEPARTAMENTO VALUES(10,'PESQUISA','SÃO PAULO');
INSERT INTO DEPARTAMENTO VALUES(20,'RH','SÃO PAULO');
INSERT INTO DEPARTAMENTO VALUES(30,'VENDAS','RIO DE JANEIRO');
INSERT INTO DEPARTAMENTO VALUES(40,'COMPRAS','PORTO ALEGRE');

INSERT INTO EMPREGADO VALUES(1004, 'Ana', 2000, 10);
INSERT INTO EMPREGADO VALUES(1005, 'Bia', 4000, 20);
INSERT INTO EMPREGADO VALUES(1006, 'Tia', 6000, 30);